# FROM golang:1.13.3-stretch

# RUN add-apt-repository \
#    "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"

# RUN apt-get update &&  apt-get install -y \
#     python-pip \
#     git \
#     docker-ce docker-ce-cli containerd.io

# RUN pip install pre-commit

# ARG version=none
# ENV VERSION=$version

# COPY entrypoint.sh /entrypoint.sh
# RUN chmod +x /entrypoint.sh

# ENTRYPOINT ["/entrypoint.sh"]

FROM docker:19.03.2
LABEL maintainer="Karsten Jakobsen <kj@patientsky.com>"

# LABEL "com.github.actions.name"="Docker build and/or publish"
# LABEL "com.github.actions.description"="docker build and/or publish to registry"
# LABEL "com.github.actions.icon"="anchor"
# LABEL "com.github.actions.color"="blue"
# LABEL "repository"="https://github.com/pasientskyhosting/github-actions"

# RUN apk update \
#   && apk upgrade \
#   && apk add --no-cache git py-pip

# RUN pip install pre-commit

# ARG version=none
# ENV VERSION=$version

COPY entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]