---

name: 'Dockerfile Linter'
description:  'Lint a Dockerfile, or many Dockerfiles'

inputs:
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
    default: './Dockerfile'

outputs:

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dockerfile }}
