---

name: 'Dockerfile Linter'
description:  'Lint a Dockerfile, or many Dockerfiles'

inputs:
  dockerfile_path:
    description: 'Path to Dockerfile'
    required: true
    default: './Dockerfile'

runs:
  using: 'docker'
  image: 'Dockerfile'
