---

name: 'Ansible Lint'
description: 'Run ansible-lint'

inputs:
  playbook_name:
    description: 'Name of playbook to lint'
    required: true 
    default: 'playbook.yml'
  
outputs:

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.playbook_name }}
