---

name: 'Ansible Lint'
description: 'Run ansible-lint'

inputs:
  playbook_name:
    description: 'Name of playbook to lint'
    required: true
    default: 'playbook.yml'
  tool_name:
    description: 'Reviewdog identifier'
    default: 'ansible_lint'
  
outputs:

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PLAYBOOK_NAME: ${{ inputs.playbook_name }}
    TOOL_NAME: ${{ inputs.tool_name }}
