---

name: Docker Build

on:
  pull_request:
    branches:
    - master

jobs:

  docker_build_job:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action: [ 'ansible-lint', 'golangci-lint', 'dockerfile-linter', 'docker-build-push']

    name: Docker Build
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Docker Build
      uses: ./docker-build-push
      with:
        image_name: pasientskyhosting/action-${{ matrix.action }}
        build_only: 'true'
        build_context: ./${{ matrix.action }}
        dockerfile_path: ./${{ matrix.action }}/Dockerfile


  docker_build_job_pre_commit:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python_version: [ 3.5.9, 3.7.7 ]

    name: Docker Build Pre Commit
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Docker Build
      uses: ./docker-build-push
      with:
        image_name: pasientskyhosting/action-pre-commit
        build_only: 'true'
        build_context: ./pre-commit
        dockerfile_path: ./pre-commit/Dockerfile
        docker_build_args: PYTHON_VERSION=${{ matrix.python_version }}
