---

name: Integration

on:
  pull_request:
    branches:
    - master
    - development

jobs:

  lint:

    runs-on: ubuntu-18.04
    name: Linters

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Dockerfile linter
      id: dockerfile
      uses: ./.github/actions/dockerfile-linter
      with:
        dockerfile: "./.github/actions/dockerfile-linter/Dockerfile"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
