---

name: Linters

on:
  pull_request:
    branches:
    - master
    - development

jobs:

  dockerfile_lint:

    runs-on: ubuntu-18.04
    name: Dockerfile Linters

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: docker-publish linter
      id: docker-publish-linter
      uses: ./dockerfile-linter
      with:
        dockerfile: ./docker-publish/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: hello-world linter
      id: hello-world-linter
      uses: ./dockerfile-linter
      with:
        dockerfile: ./hello-world/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: dockerfile-linter linter
      id: dockerfile-linter-linter
      uses: ./dockerfile-linter
      with:
        dockerfile: ./dockerfile-linter/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: golangci-lint linter
      id: golangci-lint-linter
      uses: ./dockerfile-linter
      with:
        dockerfile: ./golangci-lint/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
