---

name: Linters

on:
  pull_request:
    branches:
    - master
    - development

jobs:

  dockerfile_lint:

    runs-on: ubuntu-18.04
    name: Dockerfile Linters

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: ansible-lint linter
      id: ansible-lint-linter
      uses: ./dockerfile-linter
      with:
        dockerfile: ./ansible-lint/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: docker-build-push linter
      id: docker-build-push-linter
      uses: ./dockerfile-linter
      with:
        dockerfile: ./docker-build-push/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: hello-world linter
      id: hello-world-linter
      uses: ./dockerfile-linter
      with:
        dockerfile: ./hello-world/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: dockerfile-lint linter
      id: dockerfile-lint-linter
      uses: ./dockerfile-linter
      with:
        dockerfile: ./dockerfile-linter/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: golangci-lint linter
      id: golangci-lint-linter
      uses: ./dockerfile-linter
      with:
        dockerfile: ./golangci-lint/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
