---

name: Linters

on:
  pull_request:
    branches:
    - master

jobs:

  dockerfile_lint:

    runs-on: ubuntu-latest
    name: Dockerfile Linters
    strategy:
      fail-fast: false
      matrix:
        action: [ 'ansible-lint', 'golangci-lint', 'dockerfile-linter', 'docker-build-push', 'docker-build-push']

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: dockerfile-linter
      id: dockerfile-linter
      uses: ./dockerfile-linter
      with:
        dockerfile_path: ./${{ matrix.action }}/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
